2023-11-27 08:30:26,859:INFO:这是一条INFO级别的日志
2023-11-27 08:30:26,859:DEBUG:这是一条DEBUG级别的日志
2023-11-27 08:30:26,870:ERROR:
2023-11-27 08:30:26,870:ERROR:Processing issues:   0%|          | 0/1 [00:00<?, ?it/s]
2023-11-27 08:30:26,870:DEBUG:Processing mfem issue2878
2023-11-27 08:30:26,870:ERROR:
2023-11-27 08:30:26,870:ERROR:Processing test cases for mfem issue2878:   0%|          | 0/2 [00:00<?, ?it/s]
2023-11-27 08:30:26,871:ERROR:[A
2023-11-27 08:30:27,162:DEBUG:Deleted old branch branch_d9275d7
2023-11-27 08:30:27,316:DEBUG:Switched to new branch branch_d9275d7 at d9275d734e060fc653236ab4901b370cbb6dd7ad
2023-11-27 08:30:27,316:DEBUG:Target directory: /root/mfem-code-analyzer/bugs/issue2878
2023-11-27 08:30:27,317:DEBUG:Copied tests/unit/fem/test_pa_coeff.cpp to /root/mfem-code-analyzer/bugs/issue2878/test_pa_coeff.cpp
2023-11-27 08:30:27,317:ERROR:
2023-11-27 08:30:27,318:ERROR:Processing test cases for mfem issue2878:  50%|#####     | 1/2 [00:00<00:00,  2.24it/s]
2023-11-27 08:30:27,318:ERROR:[A
2023-11-27 08:30:27,842:DEBUG:Deleted old branch branch_d9275d7
2023-11-27 08:30:28,056:DEBUG:Switched to new branch branch_d9275d7 at d9275d734e060fc653236ab4901b370cbb6dd7ad
2023-11-27 08:30:28,057:DEBUG:Target directory: /root/mfem-code-analyzer/bugs/issue2878
2023-11-27 08:30:28,057:DEBUG:Copied tests/unit/fem/test_pa_grad.cpp to /root/mfem-code-analyzer/bugs/issue2878/test_pa_grad.cpp
2023-11-27 08:30:28,058:ERROR:
2023-11-27 08:30:28,058:ERROR:Processing test cases for mfem issue2878: 100%|##########| 2/2 [00:01<00:00,  1.61it/s]
2023-11-27 08:30:28,058:ERROR:[A
2023-11-27 08:30:28,058:ERROR:[A
2023-11-27 08:30:28,058:INFO:Processing issue: {'name': 'issue2878', 'bug_sha': '973b42c57a60ea4844dd09ff38e47ed89ead93ad', 'fix_sha': 'd9275d734e060fc653236ab4901b370cbb6dd7ad', 'testcase': 'tests/unit/fem/test_pa_coeff.cpp,tests/unit/fem/test_pa_grad.cpp', 'testname': 'H1 pa_coeff,Hcurl/Hdiv pa_coeff,Hcurl/Hdiv mixed pa_coeff,ParallelPAGradient,PA Gradient,Nonlinear Convection', 'url': 'https://github.com/mfem/mfem/commit/987d2e043bad3a99841b88354dce0c0932cb8642'}
2023-11-27 08:30:28,059:INFO:Running bug version: 973b42c57a60ea4844dd09ff38e47ed89ead93ad
2023-11-27 08:30:28,454:DEBUG:No existing branch named branch_973b42c, continue...
2023-11-27 08:30:28,648:DEBUG:Switched to new branch branch_973b42c at 973b42c57a60ea4844dd09ff38e47ed89ead93ad
2023-11-27 08:30:28,649:DEBUG:Copied fix file /root/mfem-code-analyzer/bugs/issue2878/test_pa_coeff.cpp to /root/mfem/tests/unit/fem/test_pa_coeff.cpp
2023-11-27 08:30:28,650:DEBUG:Copied fix file /root/mfem-code-analyzer/bugs/issue2878/test_pa_grad.cpp to /root/mfem/tests/unit/fem/test_pa_grad.cpp
2023-11-27 08:30:30,616:ERROR:
2023-11-27 08:30:30,617:ERROR:Processing issues:   0%|          | 0/1 [00:03<?, ?it/s]
2023-11-27 08:30:30,617:ERROR:Traceback (most recent call last):
2023-11-27 08:30:30,617:ERROR:  File "/root/mfem-code-analyzer/get_normal_testcase_covarage/run_mfme_testcase.py", line 299, in <module>
2023-11-27 08:30:30,617:ERROR:processor.process_yaml_file()
2023-11-27 08:30:30,617:ERROR:  File "/root/mfem-code-analyzer/get_normal_testcase_covarage/run_mfme_testcase.py", line 147, in process_yaml_file
2023-11-27 08:30:30,617:ERROR:self.process_mfem_issue(issue_data)
2023-11-27 08:30:30,617:ERROR:  File "/root/mfem-code-analyzer/get_normal_testcase_covarage/run_mfme_testcase.py", line 103, in process_mfem_issue
2023-11-27 08:30:30,618:ERROR:self.compile_mfem()
2023-11-27 08:30:30,618:ERROR:  File "/root/mfem-code-analyzer/get_normal_testcase_covarage/run_mfme_testcase.py", line 234, in compile_mfem
2023-11-27 08:30:30,618:ERROR:result = subprocess.run(["bash", bash_path], capture_output=True, text=True)
2023-11-27 08:30:30,618:ERROR:  File "/usr/lib/python3.10/subprocess.py", line 505, in run
2023-11-27 08:30:30,618:ERROR:stdout, stderr = process.communicate(input, timeout=timeout)
2023-11-27 08:30:30,618:ERROR:  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
2023-11-27 08:30:30,619:ERROR:stdout, stderr = self._communicate(input, endtime, timeout)
2023-11-27 08:30:30,619:ERROR:  File "/usr/lib/python3.10/subprocess.py", line 2021, in _communicate
2023-11-27 08:30:30,619:ERROR:ready = selector.select(timeout)
2023-11-27 08:30:30,619:ERROR:  File "/usr/lib/python3.10/selectors.py", line 416, in select
2023-11-27 08:30:30,619:ERROR:fd_event_list = self._selector.poll(timeout)
2023-11-27 08:30:30,619:ERROR:KeyboardInterrupt
